### PR TITLE
Merge upstream/pr 2022.02.16

### PR DESCRIPTION
**Pull request by FabienPean-Virtonomy**

### CODE REVIEW

**Comment by FabienPean-Virtonomy** [comment]
Report from CI
```
The following tests FAILED:
	  8 - test_2d_dambreak_restart (Failed)
	 29 - test_2d_self_contact (Failed)
	 32 - test_2d_sliding (Failed)
```

Removing as discussed previously @BenceVirtonomy

**Comment by FabienPean-Virtonomy** [comment]
The test was passing on previous commit [155f636](https://github.com/BenceVirtonomy/SPHinXsys/pull/71/commits/155f636141cf83bd47b310e272f4a9a2706a0afb)
It didn't pass on this round with seemingly no reason. Can we just merge at this point please ? 😄 
```
The maximum distance of Position[0] is 0.0005791, and the current distance is 0.0006224.
The DTW distance of Position between current result and this previous local result is beyond exception!
Please try again. If it still post this sentence, the result is not correct!


The following tests FAILED:
	 71 - test_3d_taylor_bar (Failed)
```

**Comment by BenceVirtonomy** [comment]
> Report from CI
> 
> ```
> The following tests FAILED:
> 	  8 - test_2d_dambreak_restart (Failed)
> 	 29 - test_2d_self_contact (Failed)
> 	 32 - test_2d_sliding (Failed)
> ```
> 
> Removing as discussed previously @BenceVirtonomy

Yes, good

**Comment by BenceVirtonomy** [comment]
> The test was passing on previous commit [155f636](https://github.com/BenceVirtonomy/SPHinXsys/pull/71/commits/155f636141cf83bd47b310e272f4a9a2706a0afb) It didn't pass on this round with seemingly no reason. Can we just merge at this point please ? 😄
> 
> ```
> The maximum distance of Position[0] is 0.0005791, and the current distance is 0.0006224.
> The DTW distance of Position between current result and this previous local result is beyond exception!
> Please try again. If it still post this sentence, the result is not correct!
> 
> 
> The following tests FAILED:
> 	 71 - test_3d_taylor_bar (Failed)
> ```

Yes, just disable it

**Review by BenceVirtonomy — APPROVED** [review]

**Review by mrezavandVirtonomy — APPROVED** [review]

**Pull request merged**
